### ISSUE TITLE
Any chance of getting this on npm?

### ISSUE THREAD

**Issue by surfjedi** [AngularPlus/AngularPlus#16]

**Comment by zackschuster** [comment]
@surfjedi my company put this up on npm under [angularplus](https://www.npmjs.com/package/angularplus) about a year ago.

would be interested in transferring it to the project owners if at all possible (cc @DanWahlin @johnpapa)

**Comment by brentmannarino** [comment]
Any chance of getting release 0.9.3 on npm?

**Comment by DanWahlin** [comment]
@johnpapa & I aren't really doing much with this project now (leaving it out there for anyone who wants it though). I don't know if @zackschuster is interested in updating that since he (or someone at his company) created the initial npm package.
